name: 'CI'

on:
    pull_request:
    push:
        branches:
            - 'master'

env:
    CONSISTENCE_PHP_VERSION: '7.3'

jobs:
    composer-validate:
        name: 'Composer validate'
        runs-on: 'ubuntu-latest'

        steps:
            -
                name: 'Checkout'
                uses: 'actions/checkout@v3'
            -
                name: 'Setup PHP ${{ env.CONSISTENCE_PHP_VERSION }}'
                uses: 'shivammathur/setup-php@v2'
                with:
                     php-version: '${{ env.CONSISTENCE_PHP_VERSION }}'
                     coverage: 'none'
            -
                name: 'Composer install'
                uses: 'ramsey/composer-install@v1'
                with:
                    dependency-versions: 'highest'
            -
                name: 'Composer validate'
                run: 'bin/phing composer-validate'
